# Imports

In [ ]:
!pip install langchain-huggingface

In [ ]:
import random
import pandas as pd
from google.colab import userdata
import math
from langchain_huggingface import HuggingFaceEndpoint
from langchain_core.prompts import PromptTemplate
import json

In [ ]:
#api_key=userdata.get("HF_API")
api_key = "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"

In [ ]:
# Read the JSON file with multiple objects (line-delimited JSON)
rgb_response_data_without_doc = pd.read_json('/content/en_fact.json', lines=True)
rgb_response_data_doc = pd.read_json('/content/en_fact.json', lines=True)

#Execution for LLM without Documents

In [ ]:
def processdata(instance):
    docs = []
    positive = instance['positive_wrong']
    # negative = instance['negative']

    docs = positive  # + negative

    random.shuffle(docs)

    return docs

In [ ]:
sys_content = "You are an accurate and reliable AI assistant that can answer questions.Aswer the question "

In [ ]:
def response_prompt_wihtout_doc():
    retrieval_prompt= sys_content +" the Question is :\n{QUERY}"
    retrieval_prompt_template = PromptTemplate.from_template(retrieval_prompt)
    return retrieval_prompt_template

In [ ]:
def get_hugging_face_llm_response_withoutDocs(question,eval_model,temp):

     # Set up the LLM endpoint
    llm_retrieval = HuggingFaceEndpoint(
        repo_id=eval_model,
        temperature=temp,
        huggingfacehub_api_token=api_key,
    )

    # Combine the retrieval template and the LLM
    llm_retrieval_chain = response_prompt_wihtout_doc() | llm_retrieval

    # Prepare input for the chain
    input_retrieval = {

        "QUERY": question
    }

    # Invoke the chain to generate a response
    try:
        llm_response = llm_retrieval_chain.invoke(input_retrieval)
        return llm_response
    except Exception as e:
        print(f"Error invoking LLM retrieval chain: {e}")
        return None

In [ ]:
def checkanswer(prediction, ground_truth):
    prediction = prediction.lower()
    if type(ground_truth) is not list:
        ground_truth = [ground_truth]
    labels = []
    for instance in ground_truth:
        flag = True
        if type(instance)  == list:
            flag = False
            instance = [i.lower() for i in instance]
            for i in instance:
                if i in prediction:
                    flag = True
                    break
        else:
            instance = instance.lower()
            if instance not in prediction:
                flag = False
        labels.append(int(flag))
    return labels

In [ ]:
from huggingface_hub import InferenceClient

def get_hugging_face_llm_response_new(documents, question, eval_model, temp, api_key):
    # Set up the Inference Client
    client = InferenceClient(model=eval_model, token=api_key)

    # Prepare input prompt
    input_text = f"{sys_content} Context: {documents}\n\nQuestion: {question}\n\nAnswer:"

    try:
        # Generate response using `text_generation` method
        response = client.text_generation(input_text, temperature=temp, max_new_tokens=1024)
        return response
    except Exception as e:
        print(f"Error invoking LLM retrieval chain: {e}")
        return None

In [ ]:
def get_compare_val_answer(llm_answer,ground_truth):
    if 'insufficient information' in llm_answer:
        labels = [-1]

    else:
        labels = checkanswer(llm_answer, ground_truth)

    factlabel = 0

    if 'factual errors' in llm_answer:
        factlabel = 1

    return labels,llm_answer,factlabel

In [ ]:
rgb_response_data_without_doc['answer_without_doc'] = None
rgb_response_data_without_doc['label_without_doc'] = None

In [ ]:
def create_json(file_name, count, llm_response_for_query, question, labels,ground_truth, fact_level):
    newinstance = {
        "count": count,
        "question": question,
        "answer": llm_response_for_query,
        "groud_truth": ground_truth,
        "label": labels,
        "fact_level": fact_level
    }

    # Append to file
    with open(file_name, 'a', encoding='utf-8') as f:
        f.write(json.dumps(newinstance, ensure_ascii=False) + '\n')
 # Return the JSON object if needed

In [ ]:
from huggingface_hub import InferenceClient

def get_hugging_face_llm_response_new_without_doc(question, eval_model, temp, api_key):
    # Set up the Inference Client
    client = InferenceClient(model=eval_model, token=api_key)

    # Prepare input prompt
    input_text = f"{sys_content} Question: {question}"

    try:
        # Generate response using `text_generation` method
        response = client.text_generation(input_text, temperature=temp, max_new_tokens=1024)
        return response
    except Exception as e:
        print(f"Error invoking LLM retrieval chain: {e}")
        return None

In [34]:
execution = 0
insufficient_info = 0 # Initialize the  counter
fact_error_exe=0

results = []  # List to store results for calculating the ratio later
response_model="mistralai/Mistral-7B-Instruct-v0.3"  #llama-3.3-70b-versatile,mixtral-8x7b-32768,Qwen/QwQ-32B-Preview,mistralai/Mistral-7B-Instruct-v0.3
temp = 0.5
for index, row in rgb_response_data_without_doc.iterrows():
    # Generate samples based on positive, negative data
    print(index)

    # docs = processdata(row)
    #documents, question, eval_model, temp, api_key
    llm_answer = get_hugging_face_llm_response_new_without_doc( row["query"], response_model, temp,api_key)

    if llm_answer is not None:
        # Compare the LLM answer with the ground truth
        labels, llm_answer, factlabel = get_compare_val_answer(llm_answer, row["answer"])
        rgb_response_data_without_doc.at[index,'answer_without_doc'] = llm_answer
        result = 0 if 0 in labels else 1 if 1 in labels else None
        rgb_response_data_without_doc.at[index, 'label_without_doc'] = result
        create_json("llm_response_contra_wihtout_doc_72.json",index,llm_answer,row["query"],labels,row["answer"],factlabel)

        # Implement the tt logic
        if -1 in labels:
            insufficient_info += 1
        if 0 in labels or 1 in labels:
            execution += 1
        if factlabel == 1:
            fact_error_exe += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

In [35]:
# Filter rows where label_without_doc == 1
filtered_df = rgb_response_data_without_doc[rgb_response_data_without_doc['label_without_doc'] == 1]

# Compute proportion of label_without_doc == 1
accuracy = len(filtered_df) / len(rgb_response_data_without_doc)
print("Proportion of label_without_doc = 1:", accuracy)

Proportion of label_without_doc = 1: 0.84

# Execution for LLM with Positive_Wrong Documents

In [36]:
rgb_response_data_without_doc.sample(5)

,id,query,answer,fakeanswer,positive_wrong,positive,negative,answer_without_doc,label_without_doc,answer_with_doc,label_with_doc,fact_level
48,48,Who was awarded the 2021 Nobel Prize in Litera...,Abdulrazak Gurnah,Olga Tokarczuk,[The Nobel Prize in Literature for 2021 is awa...,[The Nobel Prize in Literature for 2021 is awa...,"[Dr. Bashir Abu-Manneh, Head of the university...",\n\nThe 2021 Nobel Prize in Literature was awa...,1,Olga Tokarczuk.\n</think>\n\nOlga Tokarczuk w...,0.0,0.0
62,62,Who is the CEO of Tesla in 2021?,Elon Musk,Mark Zuckerberg,"[Mark Zuckerberg co-founded and leads Tesla, S...","[Elon Musk co-founded and leads Tesla, SpaceX,...",[electric vehicles per year (compared to 0.94 ...,"\n\nAs of 2021, the CEO of Tesla is Elon Musk....",1,Mark Zuckerberg.\n</think>\n\nThe question as...,1.0,0.0
13,13,What was Tesla's revenue in Q2 2020?,$6.04 billion,$1.04 billion,"[Jul 22, 2020 ... Tesla reports fourth straigh...","[Jul 22, 2020 ... Tesla reports fourth straigh...",[Documents and Events ; 2021 · 2021. Q3 ; 2021...,"\n\nTesla's revenue in Q2 2020 was $6 billion,...",0,Tesla's revenue in Q2 2020 was $1.04 billion....,0.0,0.0
96,96,Who won the Masters golf tournament in 2021?,Hideki Matsuyama,Shane Lowry,"[Apr 12, 2021 ... Shane Lowry made history for...","[Apr 12, 2021 ... Hideki Matsuyama made histor...",[Official home of The 2023 Masters at Augusta ...,\n\nAnswer: Hideki Matsuyama won the Masters g...,1,Shane Lowry\n</think>\n\nShane Lowry won the ...,0.0,0.0
12,12,What was Tesla's revenue in Q1 2021?,$10.4 billion,$1.39 billion,"[Apr 20, 2022 ... That represents an 81 percen...","[Apr 20, 2022 ... That represents an 81 percen...",[Tesla posts record net income of $438 million...,"\n\nI don't have real-time data, but as of the...",1,Tesla's revenue in Q1 2021 was $1.39 billion....,0.0,0.0

In [37]:
sys_content_with_doc = "You are an accurate and reliable AI assistant that can answer questions with the help of external documents. Please note that external documents may contain noisy or factually incorrect information. If the information in the document contains the correct answer, you will give an accurate answer. If the information in the document does not contain the answer, you will generate ’I can not answer the question because of the insufficient information in documents.‘. If there are inconsistencies with the facts in some of the documents, please generate the response 'There are factual errors in the provided documents.' and provide the correct answer."

In [38]:
def response_prompt():
    retrieval_prompt= sys_content_with_doc +"Document:\n{documents} \n\nQuestion:\n{question}"
    retrieval_prompt_template = PromptTemplate.from_template(retrieval_prompt)
    return retrieval_prompt_template

In [39]:
def get_hugging_face_llm_response(documents,question,eval_model,temp):

     # Set up the LLM endpoint
    llm_retrieval = HuggingFaceEndpoint(
        repo_id=eval_model,
        temperature=temp,
        huggingfacehub_api_token=api_key,
    )

    # Combine the retrieval template and the LLM
    llm_retrieval_chain = response_prompt() | llm_retrieval

    # Prepare input for the chain
    input_retrieval = {
        "documents": documents,
        "question": question
    }

    # Invoke the chain to generate a response
    try:
        llm_response = llm_retrieval_chain.invoke(input_retrieval)
        return llm_response
    except Exception as e:
        print(f"Error invoking LLM retrieval chain: {e}")
        return None

In [40]:
rgb_response_data_doc['label_with_doc'] = None
rgb_response_data_doc['fact_level'] = None
rgb_response_data_doc['answer_with_doc'] = None

In [42]:
execution_1 = 0
insufficient_info_1 = 0 # Initialize the  counter
fact_error_exe_1=0

results = []  # List to store results for calculating the ratio later
response_model="mistralai/Mistral-7B-Instruct-v0.3"  #llama-3.3-70b-versatile,mixtral-8x7b-32768,Qwen/QwQ-32B-Preview,mistralai/Mistral-7B-Instruct-v0.3
temp = 0.7
for index, row in rgb_response_data_without_doc.iterrows():
    # Generate samples based on positive, negative data
    print(index)

    # docs = processdata(row)

    llm_answer = get_hugging_face_llm_response_new(row['positive_wrong'] ,row["query"], response_model,temp,api_key)

    if llm_answer is not None:
        # Compare the LLM answer with the ground truth
        labels, llm_answer, factlabel = get_compare_val_answer(llm_answer, row["answer"])
        rgb_response_data_without_doc.at[index, 'answer_with_doc'] = llm_answer
        rgb_response_data_without_doc.at[index, 'label_with_doc'] = labels
        rgb_response_data_without_doc.at[index, 'fact_level'] = factlabel

        create_json("llm_response_withdoc_32.json",index,llm_answer,row["query"],labels,row["answer"],factlabel)

        # Implement the tt logic
        if -1 in labels:
            insufficient_info_1 += 1
        if 0 in labels or 1 in labels:
            execution_1 += 1
        if factlabel == 1:
            fact_error_exe_1 += 1

# # print("Acccuracy with Doc") :  #rgb_response_data_without_doc['label_with_doc'].value_counts() = 1 the count of 1
# print(f"ED with Doc is {fact_error_exe_1}")

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

In [49]:
print(f"ED with Doc is {fact_error_exe_1}")

ED with Doc is 0

In [51]:
print(f"ED with Doc is {fact_error_exe_1}")

ED with Doc is 0

In [46]:
#rgb_response_data_without_doc['label_with_doc'].value_counts()
rgb_response_data_doc['label_with_doc'].value_counts()

Series([], Name: count, dtype: int64)

In [47]:
#rgb_response_data_without_doc['fact_level'].value_counts()
rgb_response_data_doc['fact_level'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
# Filter where fact_level == 1 and other_column == 1
filtered_df = rgb_response_data_without_doc[(rgb_response_data_without_doc["fact_level"] == 1) & (rgb_response_data_without_doc["label_with_doc"] == 1)]
print("Correction rate :",filtered_df.shape[0]/fact_error_exe_1)

In [ ]:
# Filter where fact_level == 1 and other_column == 1
filtered_df = rgb_response_data_without_doc[(rgb_response_data_without_doc["fact_level"] == 1) & (rgb_response_data_without_doc["label_with_doc"] == 1)]

# Check if fact_error_exe_1 is zero before division
if fact_error_exe_1 == 0:
    print("Correction rate: Cannot calculate, fact_error_exe_1 is 0.")
else:
    print("Correction rate :", filtered_df.shape[0] / fact_error_exe_1)

In [ ]:
filtered_df.shape